spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FitnessActivities
      database: FitnessActivities
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8767/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    name: activity.routing